name: Cortography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#3d4a50'
    - '#818586'
    - '#b9b7ac'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.8587160168681294
  rhythmicContrast: 0.10550989978946745
purpose: []
